#NNPPSS Configuration
#Wed Feb 11 00:35:38 AST 2026
autoCleanupPkg=true
darkMode=false
downloadSpeedLimit=0
language=en
psp.url=https\://nopaystation.com/tsv/PSP_GAMES.tsv
psvita.url=https\://nopaystation.com/tsv/PSV_GAMES.tsv
psx.url=https\://nopaystation.com/tsv/PSX_GAMES.tsv
simultaneousDownloads=4
