/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.squarepeace.nnppss;

import com.squarepeace.nnppss.model.Console;
import com.squarepeace.nnppss.model.Game;
import com.squarepeace.nnppss.service.ConfigManager;
import com.squarepeace.nnppss.service.DownloadService;
import com.squarepeace.nnppss.service.GameRepository;
import com.squarepeace.nnppss.service.PackageService;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Vector;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class Frame extends javax.swing.JFrame implements ActionListener {

    private DefaultTableModel originalModel;
    private TableRowSorter<DefaultTableModel> rowSorter;

    private final ConfigManager configManager;
    private final GameRepository gameRepository;
    private final DownloadService downloadService;
    private final PackageService packageService;

    private boolean downloadPaused = false;
    private boolean downloading = false;

    private List<Game> downloadList = new ArrayList<>();

    public Frame(ConfigManager configManager, GameRepository gameRepository, DownloadService downloadService, PackageService packageService) {
        this.configManager = configManager;
        this.gameRepository = gameRepository;
        this.downloadService = downloadService;
        this.packageService = packageService;
        
        initComponents();
        jbResumeAndPause.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgConsoles = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jbsearch = new javax.swing.JLabel();
        jbRefresh = new javax.swing.JButton();
        jtfSearch = new javax.swing.JTextField();
        jcbRegion = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbSetting = new javax.swing.JButton();
        jrbPsvita = new javax.swing.JRadioButton();
        jrbPsp = new javax.swing.JRadioButton();
        jbDownloadList = new javax.swing.JButton();
        jrbPsx = new javax.swing.JRadioButton();
        jpbDownload = new javax.swing.JProgressBar();
        jbResumeAndPause = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NNPPSS");

        jPanel1.setName("NNPPSS"); // NOI18N

        jbsearch.setText("Search:");

        jbRefresh.setText("Refresh");
        jbRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRefreshActionPerformed(evt);
            }
        });

        jtfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfSearchKeyReleased(evt);
            }
        });

        jcbRegion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbRegionItemStateChanged(evt);
            }
        });

        jtData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtDataMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtData);

        jLabel1.setText("Region: ");

        jLabel2.setText("Console:");

        jbSetting.setText("Setting");
        jbSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSettingActionPerformed(evt);
            }
        });

        bgConsoles.add(jrbPsvita);
        jrbPsvita.setText("Psvita");
        jrbPsvita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPsvitaActionPerformed(evt);
            }
        });

        bgConsoles.add(jrbPsp);
        jrbPsp.setText("Psp");
        jrbPsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPspActionPerformed(evt);
            }
        });

        jbDownloadList.setText("Download list");
        jbDownloadList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDownloadListActionPerformed(evt);
            }
        });

        bgConsoles.add(jrbPsx);
        jrbPsx.setText("Psx");
        jrbPsx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPsxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbPsvita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbPsp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbPsx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbDownloadList, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jcbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbsearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jbRefresh)
                .addGap(18, 18, 18)
                .addComponent(jbSetting)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbsearch)
                    .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbRefresh)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jbSetting)
                    .addComponent(jrbPsvita)
                    .addComponent(jrbPsp)
                    .addComponent(jbDownloadList)
                    .addComponent(jrbPsx))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpbDownload.setStringPainted(true);

        jbResumeAndPause.setText("Pause");
        jbResumeAndPause.setActionCommand(":p");
        jbResumeAndPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbResumeAndPauseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jpbDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbResumeAndPause)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpbDownload, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jbResumeAndPause))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void jtDataMousePressed(java.awt.event.MouseEvent evt) {
        int selectedRow = jtData.getSelectedRow();
        if (selectedRow != -1) {
            int modelRowIndex = jtData.convertRowIndexToModel(selectedRow);
            DefaultTableModel model = (DefaultTableModel) jtData.getModel();

            String pkgUrl = (String) model.getValueAt(modelRowIndex, getColumnIndexByName("PKG direct link"));
            
            if ("MISSING".equals(pkgUrl)) {
                JOptionPane.showMessageDialog(this, "You cannot download this game because the download link is not registered.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else if ("CART ONLY".equals(pkgUrl)) {
                JOptionPane.showMessageDialog(this, "This game is available in cart only.", "Information", JOptionPane.INFORMATION_MESSAGE);
                return;
            } else if ("NOT REQUIRED".equals(pkgUrl)) {
                JOptionPane.showMessageDialog(this, "No download required", "Information", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            String name = (String) model.getValueAt(modelRowIndex, getColumnIndexByName("Name"));
            String fileSize = (String) model.getValueAt(modelRowIndex, getColumnIndexByName("File Size"));
            String zRif = (String) model.getValueAt(modelRowIndex, getColumnIndexByName("zRIF"));
            String region = (String) model.getValueAt(modelRowIndex, getColumnIndexByName("Region"));

            int option = JOptionPane.showConfirmDialog(this,
                    "Do you want to add " + name + " (" + fileSize + ") to download list?",
                    "Download List",
                    JOptionPane.YES_NO_OPTION);

            if (option == JOptionPane.YES_OPTION) {
                if (downloadList.stream().anyMatch(g -> g.getPkgUrl().equals(pkgUrl))) {
                    JOptionPane.showMessageDialog(this, "The game is already in the download list.");
                    return;
                }

                Game game = new Game();
                game.setTitle(name);
                game.setPkgUrl(pkgUrl);
                game.setzRif(zRif);
                game.setRegion(region);
                
                if (jrbPsp.isSelected()) game.setConsole(Console.PSP);
                else if (jrbPsvita.isSelected()) game.setConsole(Console.PSVITA);
                else if (jrbPsx.isSelected()) game.setConsole(Console.PSX);

                downloadList.add(game);
                System.out.println("Added to list: " + game);
            }
        }
    }

    private void jbDownloadListActionPerformed(java.awt.event.ActionEvent evt) {
        JTable table = new JTable();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.addColumn("Name");
        model.addColumn("Region");
        model.addColumn("Console");
        model.addColumn("URL");

        for (Game game : downloadList) {
            model.addRow(new Object[]{game.getTitle(), game.getRegion(), game.getConsole(), game.getPkgUrl()});
        }

        JButton removeButton = new JButton("Remove Selected");
        removeButton.addActionListener(e -> {
            int[] selectedRows = table.getSelectedRows();
            for (int i = selectedRows.length - 1; i >= 0; i--) {
                int modelRow = table.convertRowIndexToModel(selectedRows[i]);
                String url = (String) model.getValueAt(modelRow, 3);
                downloadList.removeIf(g -> g.getPkgUrl().equals(url));
                model.removeRow(modelRow);
            }
        });

        JButton clearButton = new JButton("Clear List");
        clearButton.addActionListener(e -> {
            downloadList.clear();
            model.setRowCount(0);
        });

        JButton downloadButton = new JButton("Download");
        downloadButton.addActionListener(this);

        JOptionPane.showMessageDialog(null, new Object[]{new JScrollPane(table), downloadButton, removeButton, clearButton}, "Download List", JOptionPane.PLAIN_MESSAGE);
    }// GEN-LAST:event_jtDataMousePressed

    private void jbResumeAndPauseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbResumeAndPauseActionPerformed
        // Cambiar el estado de la descarga
        downloadPaused = !downloadPaused;
        // Actualizar el texto del botón
        if (downloadPaused) {
            jbResumeAndPause.setText("Resume");
        } else {
            jbResumeAndPause.setText("Pause");
        }
    }// GEN-LAST:event_jbResumeAndPauseActionPerformed

    private void jbSettingActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbSettingActionPerformed
        Config config = new Config(configManager);
        config.setLocationRelativeTo(null);
        config.setResizable(false);
        config.setVisible(true);

        // metodo para cargar los valores de las url en los campos de texto desde el
        // archivo config.properties
        config.loadValues();

    }// GEN-LAST:event_jbSettingActionPerformed

    private void jrbPspActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jrbPspActionPerformed
        fillTable();
    }// GEN-LAST:event_jrbPspActionPerformed

    // si el usuario selecciona la consola psp, se cargan los datos de la consola
    // psp, si selecciona psvita, se cargan los datos de psvita por medio de los
    // metodos fillTableAndComboBoxPsp y fillTableAndComboBoxVita usando
    // JradioButton para seleccionar la consola "jrbPsp" y "jrbPsvita

    public void fillTable() {
        if (jrbPsp.isSelected()) {
            fillTableAndComboBox("Psp");
        } else if (jrbPsvita.isSelected()) {
            fillTableAndComboBox("Psvita");
        } else if (jrbPsx.isSelected()) {
            fillTableAndComboBox("Psx");
        }
    }

    public void fillTableAndComboBox(String consoleName) {
        Console console;
        try {
            console = Console.fromDisplayName(consoleName);
        } catch (IllegalArgumentException e) {
            e.printStackTrace();
            return;
        }

        List<Game> games;
        try {
            games = gameRepository.loadGames(console);
        } catch (Exception e) {
            e.printStackTrace();
            return;
        }

        // Define columns expected by the UI
        String[] columnNames = {"Name", "Region", "PKG direct link", "zRIF", "File Size"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        for (Game game : games) {
            model.addRow(new Object[]{
                    game.getTitle(),
                    game.getRegion(),
                    game.getPkgUrl(),
                    game.getzRif(),
                    convertFileSize(game.getFileSize())
            });
        }

        originalModel = model;
        jtData.setModel(model);

        // Create the TableRowSorter
        rowSorter = new TableRowSorter<>(model);
        jtData.setRowSorter(rowSorter);

        // Update Region ComboBox
        int regionColumnIndex = 1; // "Region" is at index 1
        Set<String> regionSet = new HashSet<>();
        for (int row = 0; row < model.getRowCount(); row++) {
            String region = (String) model.getValueAt(row, regionColumnIndex);
            if (region != null) {
                regionSet.add(region);
            }
        }

        jcbRegion.removeAllItems();
        jcbRegion.addItem("All regions");
        for (String region : regionSet) {
            jcbRegion.addItem(region);
        }
    }

    private String convertFileSize(long fileSize) {
        double fileSizeMiB = fileSize / (1024 * 1024.0);
        return String.format("%.1f MiB", fileSizeMiB);
    }

    private void filtrarTablaPorTextoYRegion(String searchText, String region) {
        System.out.println("Search Text: " + searchText);
        System.out.println("Region: " + region);
        
        if (region == null) {
            return;
        }

        // Crear un RowFilter para filtrar por el texto ingresado y la región
        // seleccionada
        RowFilter<DefaultTableModel, Integer> rowFilterByText = null;
        RowFilter<DefaultTableModel, Integer> rowFilterByRegion = null;
        try {
            // Filtrar por texto ingresado
            rowFilterByText = RowFilter.regexFilter("(?i)" + searchText); // Ignore case
            System.out.println("Row Filter By Text: " + rowFilterByText);
            // Filtrar por región seleccionada si no se selecciona "Todas las regiones"
            if (!region.equals("All regions")) {
                rowFilterByRegion = RowFilter.regexFilter("(?i)" + region, getColumnIndexByName("Region"));
                System.out.println("Row Filter By Region: " + rowFilterByRegion);
            }

            // Combinar los filtros
            List<RowFilter<DefaultTableModel, Integer>> filters = new ArrayList<>();
            if (rowFilterByText != null)
                filters.add(rowFilterByText);
            if (rowFilterByRegion != null)
                filters.add(rowFilterByRegion);

            RowFilter<DefaultTableModel, Integer> combinedRowFilter = RowFilter.andFilter(filters);

            // Establecer el RowFilter en el TableRowSorter
            rowSorter.setRowFilter(combinedRowFilter);
        } catch (java.util.regex.PatternSyntaxException e) {
            e.printStackTrace(); // Imprimir la traza de la excepción para depuración
            // Si hay un error en la expresión regular, simplemente no aplicamos ningún
            // filtro
            rowSorter.setRowFilter(null);
            return;
        }
    }

    private int getColumnIndexByName(String columnName) {
        for (int i = 0; i < originalModel.getColumnCount(); i++) {
            if (originalModel.getColumnName(i).equals(columnName)) {
                return i;
            }
        }
        return -1; // Si no se encuentra la columna, retornar -1
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getActionCommand().equals("Download")) {
            startDownloads();
        }
    }

    private void startDownloads() {
        if (downloadList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "The download list is empty.");
            return;
        }

        if (downloading) {
            JOptionPane.showMessageDialog(this, "Downloads in progress.");
            return;
        }

        downloading = true;
        jbResumeAndPause.setEnabled(true);

        new Thread(() -> {
            ExecutorService executor = Executors.newFixedThreadPool(1);

            for (Game game : new ArrayList<>(downloadList)) {
                executor.submit(() -> {
                    String fileName = game.getFileName();
                    String destPath = "games/" + fileName;

                    downloadService.downloadFile(game.getPkgUrl(), destPath, new DownloadService.DownloadListener() {
                        @Override
                        public void onProgress(long bytesDownloaded, long totalBytes) {
                            int progress = (int) (bytesDownloaded * 100 / totalBytes);
                            SwingUtilities.invokeLater(() -> {
                                jpbDownload.setValue(progress);
                                jpbDownload.setString(game.getTitle() + ": " + progress + "%");
                            });
                        }

                        @Override
                        public void onComplete(File file) {
                            SwingUtilities.invokeLater(() -> {
                                jpbDownload.setValue(100);
                                jpbDownload.setString(game.getTitle() + " Completed");
                            });

                            if (game.getzRif() != null && !game.getzRif().isEmpty()) {
                                packageService.extractPackage(fileName, game.getzRif(), game.getConsole());
                            }
                        }

                        @Override
                        public void onError(Exception e) {
                            e.printStackTrace();
                            SwingUtilities.invokeLater(() -> {
                                JOptionPane.showMessageDialog(Frame.this, "Error downloading " + game.getTitle());
                            });
                        }
                    });
                });
            }

            executor.shutdown();
            try {
                executor.awaitTermination(Long.MAX_VALUE, java.util.concurrent.TimeUnit.NANOSECONDS);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

            downloading = false;
            SwingUtilities.invokeLater(() -> {
                jbResumeAndPause.setEnabled(false);
                jpbDownload.setString("All downloads completed");
                downloadList.clear();
            });

        }).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgConsoles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDownloadList;
    private javax.swing.JButton jbRefresh;
    private javax.swing.JButton jbResumeAndPause;
    private javax.swing.JButton jbSetting;
    private javax.swing.JLabel jbsearch;
    private javax.swing.JComboBox<String> jcbRegion;
    private javax.swing.JProgressBar jpbDownload;
    private javax.swing.JRadioButton jrbPsp;
    private javax.swing.JRadioButton jrbPsvita;
    private javax.swing.JRadioButton jrbPsx;
    private javax.swing.JTable jtData;
    private javax.swing.JTextField jtfSearch;
    // End of variables declaration//GEN-END:variables

    private void jbRefreshActionPerformed(java.awt.event.ActionEvent evt) {
        fillTable();
    }

    private void jtfSearchKeyPressed(java.awt.event.KeyEvent evt) {
        filtrarTablaPorTextoYRegion(jtfSearch.getText(), (String) jcbRegion.getSelectedItem());
    }

    private void jtfSearchKeyReleased(java.awt.event.KeyEvent evt) {
        filtrarTablaPorTextoYRegion(jtfSearch.getText(), (String) jcbRegion.getSelectedItem());
    }

    private void jcbRegionItemStateChanged(java.awt.event.ItemEvent evt) {
        filtrarTablaPorTextoYRegion(jtfSearch.getText(), (String) jcbRegion.getSelectedItem());
    }

    private void jrbPsvitaActionPerformed(java.awt.event.ActionEvent evt) {
        fillTable();
    }

    private void jrbPsxActionPerformed(java.awt.event.ActionEvent evt) {
        fillTable();
    }
}
